=== joedayz/javaee-with-websphere-samples/CodeJava/mapping/Accounts.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://itso.xml.com" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:itso="http://itso.xml.com">

   <complexType name="Account">
    	<sequence>
    		<element name="accountID">
    			<simpleType>
    				<restriction base="string">
    					<pattern value="[0-9]{6,8}"></pattern>
    				</restriction>
    			</simpleType>
    		</element>
    		<element name="accountType">
    			<simpleType>
    				<restriction base="string">
    					<enumeration value="Savings"></enumeration>
    					<enumeration value="Loan"></enumeration>
    					<enumeration value="Fixed"></enumeration>
    				</restriction>
    			</simpleType>
    		</element>
    		<element name="balance" type="decimal"></element>
    		<element name="interest">
    			<simpleType>
    				<restriction base="decimal">
    					<minExclusive value="0"></minExclusive>
    					<maxExclusive value="100"></maxExclusive>
    				</restriction>
    			</simpleType>
    		</element>
    		<element name="customerInfo">
    			<complexType>
    				<sequence>
    					<element name="firstName" type="string"></element>
    					<element name="lastName" type="string"></element>
    					<element name="phoneNumber">
    						<simpleType>
    							<restriction base="string">
    								<pattern
    									value="\([0-9]{3}\) [0-9]{3}-[0-9]{4}">
    								</pattern>
    							</restriction>
    						</simpleType>
    					</element>
    				</sequence>
    			</complexType></element>
    	</sequence>
    </complexType>

    <element name="accounts">
    	<complexType>
    		<sequence>
    			<element name="account" type="itso:Account" minOccurs="1" maxOccurs="unbounded"></element>
    		</sequence>
    	</complexType>
    </element>
</schema>

=== joedayz/javaee-with-websphere-samples/CodeJava/mapping/Accounts.xml
<?xml version="1.0" encoding="UTF-8"?>
<itso:accounts xmlns:itso="http://itso.xml.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://itso.xml.com Accounts.xsd ">
  <itso:account>
    <itso:accountID>itso:accountID</itso:accountID>
    <itso:accountType>Savings</itso:accountType>
    <itso:balance>0.0</itso:balance>
    <itso:interest>0.0</itso:interest>
    <itso:customerInfo>
      <itso:firstName>itso:firstName</itso:firstName>
      <itso:lastName>itso:lastName</itso:lastName>
      <itso:phoneNumber>itso:phoneNumber</itso:phoneNumber>
    </itso:customerInfo>
  </itso:account>
</itso:accounts>
